Repository camaraproject/QualityOnDemand, pull requests merged in 2025-01, with the labels that each got.

#391 Update error responses and test cases to comply with Commonalities 0.5.0
  code/API_definitions/qod-provisioning.yaml
  code/API_definitions/qos-profiles.yaml
  code/API_definitions/quality-on-demand.yaml
  code/Test_definitions/qod-provisioning-createProvisioning.feature
  code/Test_definitions/qod-provisioning-deleteProvisioning.feature
  code/Test_definitions/qod-provisioning-getProvisioningById.feature
  code/Test_definitions/qod-provisioning-retrieveProvisioningByDevice.feature
  code/Test_definitions/qos-profiles-getQosProfile.feature
  code/Test_definitions/qos-profiles-retrieveQoSProfiles.feature
  code/Test_definitions/quality-on-demand-createSession.feature
  code/Test_definitions/quality-on-demand-deleteSession.feature
  code/Test_definitions/quality-on-demand-extendQosSessionDuration.feature
  code/Test_definitions/quality-on-demand-getSession.feature
  code/Test_definitions/quality-on-demand-retrieveSessionsByDevice.feature
Labels: Spring25

#395 Updating the intro to the QoS Profile.
  code/API_definitions/qos-profiles.yaml
Labels: Spring25

#409 Updated documentation, aligned with CAMARA glossary and ICM 0.3.0
  code/API_definitions/qod-provisioning.yaml
  code/API_definitions/qos-profiles.yaml
  code/API_definitions/quality-on-demand.yaml
  documentation/API_documentation/QoSProfile_Mapping_Table.md
Labels: documentation, correction, Spring25

#412 Update 429 error responses to align with Commonalities 0.5.0-rc.1 changes
  code/API_definitions/qod-provisioning.yaml
  code/API_definitions/qos-profiles.yaml
  code/API_definitions/quality-on-demand.yaml
Labels: correction, Spring25

#384 Add L4S/DSCP support to QoS Profile
  code/API_definitions/qos-profiles.yaml
Labels: Spring25

#400 Use common artifact for device test scenarios
  code/Test_definitions/README.md
  code/Test_definitions/qod-provisioning-createProvisioning.feature
  code/Test_definitions/qod-provisioning-retrieveProvisioningByDevice.feature
  code/Test_definitions/qos-profiles-retrieveQoSProfiles.feature
  code/Test_definitions/quality-on-demand-createSession.feature
  code/Test_definitions/quality-on-demand-retrieveSessionsByDevice.feature
Labels: Spring25
